name: Upload Replay

on:
  push:
    branches:
      - main
  schedule:
    - cron: '*/10 * * * *' # Check every 10 minutes

jobs:
  upload:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Git
      run: |
        git config --global user.name "${{ secrets.GIT_USERNAME }}"
        git config --global user.email "${{ secrets.GIT_EMAIL }}"
      env:
        GIT_USERNAME: ${{ secrets.GIT_USERNAME }}
        GIT_EMAIL: ${{ secrets.GIT_EMAIL }}

    - name: Upload replays
      run: |
        git remote set-url origin "https://${{ secrets.ACCESS_TOKEN }}@github.com/mixmg/ogv.git"
        cp -r "$PWD/videos/*.mp4" videos/
        git add videos/
        git commit -m "Add new replay"
        git push origin main
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
